//! XLA typed-FFI handlers, generated by the internal `#[xla_handler]` proc-macro.
//!
//! Each body is ordinary safe Rust over [`Buf`]/[`BufMut`] (which `Deref` to
//! slices and carry their shape); the macro emits the `#[no_mangle] extern "C"`
//! wrapper, the frame decode (arguments in order, results in order), the
//! `# Safety` doc and the panic/error guard.

use crate::call_frame::{Buf, BufMut};
use crate::engine::{self, Scalar};
use crate::error::ErrorInfo;
use crate::klu::C64;
use klujax_ffi_macros::xla_handler;

// ---- shared helpers -------------------------------------------------------

fn scalar_u64(buf: &Buf<u64>) -> Result<u64, ErrorInfo> {
    if buf.len() != 1 {
        return Err(ErrorInfo::invalid("symbolic must be scalar"));
    }
    if buf[0] == 0 {
        return Err(ErrorInfo::invalid("symbolic pointer is null"));
    }
    Ok(buf[0])
}

fn dims3(dims: &[i64]) -> Result<(usize, usize, usize), ErrorInfo> {
    if dims.len() != 3 {
        return Err(ErrorInfo::invalid(
            "x must be normalized to 3D (n_lhs, n_col, n_rhs)",
        ));
    }
    Ok((dims[0] as usize, dims[1] as usize, dims[2] as usize))
}

fn write<T: Copy>(out: &mut [T], src: &[T]) -> Result<(), ErrorInfo> {
    if out.len() != src.len() {
        return Err(ErrorInfo::invalid("output size mismatch"));
    }
    out.copy_from_slice(src);
    Ok(())
}

// ---- handlers -------------------------------------------------------------

#[xla_handler(export = "analyze")]
fn analyze_h(
    ai: Buf<i32>,
    aj: Buf<i32>,
    n_col: Buf<i32>,
    mut symbolic: BufMut<u64>,
) -> Result<(), ErrorInfo> {
    let sym = engine::analyze_raw(n_col[0] as usize, &ai, &aj)?;
    symbolic[0] = sym;
    Ok(())
}

#[xla_handler(scalars(f64 => "factor_f64", C64 => "factor_c128"))]
fn factor<T: Scalar>(
    ai: Buf<i32>,
    aj: Buf<i32>,
    ax: Buf<T>,
    sym: Buf<u64>,
    mut numeric: BufMut<u64>,
) -> Result<(), ErrorInfo> {
    let n_lhs = ax.dims()[0] as usize;
    let handles = engine::factor_batch_raw(&ai, &aj, &ax, n_lhs, scalar_u64(&sym)?)?;
    write(&mut numeric, &handles)
}

#[xla_handler(scalars(f64 => "refactor_f64", C64 => "refactor_c128"))]
fn refactor<T: Scalar>(
    ai: Buf<i32>,
    aj: Buf<i32>,
    ax: Buf<T>,
    sym: Buf<u64>,
    numeric: Buf<u64>,
    mut out_numeric: BufMut<u64>,
) -> Result<(), ErrorInfo> {
    let n_lhs = ax.dims()[0] as usize;
    let handles = engine::refactor_batch_raw(&ai, &aj, &ax, n_lhs, scalar_u64(&sym)?, &numeric)?;
    write(&mut out_numeric, &handles)
}

#[xla_handler(scalars(f64 => "solve_f64", C64 => "solve_c128"))]
fn solve<T: Scalar>(
    ai: Buf<i32>,
    aj: Buf<i32>,
    ax: Buf<T>,
    b: Buf<T>,
    mut x: BufMut<T>,
) -> Result<(), ErrorInfo> {
    let (n_lhs, n_col, n_rhs) = dims3(b.dims())?;
    let out = engine::solve_raw(&ai, &aj, &ax, &b, n_lhs, n_col, n_rhs)?;
    write(&mut x, &out)
}

#[xla_handler(scalars(f64 => "solve_with_symbol_f64", C64 => "solve_with_symbol_c128"))]
fn solve_with_symbol<T: Scalar>(
    ai: Buf<i32>,
    aj: Buf<i32>,
    ax: Buf<T>,
    b: Buf<T>,
    sym: Buf<u64>,
    mut x: BufMut<T>,
) -> Result<(), ErrorInfo> {
    let (n_lhs, n_col, n_rhs) = dims3(b.dims())?;
    let out =
        engine::solve_with_symbol_raw(&ai, &aj, &ax, &b, n_lhs, n_col, n_rhs, scalar_u64(&sym)?)?;
    write(&mut x, &out)
}

#[xla_handler(scalars(f64 => "tsolve_with_symbol_f64", C64 => "tsolve_with_symbol_c128"))]
fn tsolve_with_symbol<T: Scalar>(
    ai: Buf<i32>,
    aj: Buf<i32>,
    ax: Buf<T>,
    b: Buf<T>,
    sym: Buf<u64>,
    mut x: BufMut<T>,
) -> Result<(), ErrorInfo> {
    let (n_lhs, n_col, n_rhs) = dims3(b.dims())?;
    let out =
        engine::tsolve_with_symbol_raw(&ai, &aj, &ax, &b, n_lhs, n_col, n_rhs, scalar_u64(&sym)?)?;
    write(&mut x, &out)
}

/// Infer `(n_lhs, n_col, n_rhs, broadcast_b)` for `solve_with_numeric` from the
/// operand shape and the numeric batch size (mirrors the C++ handler).
fn numeric_dims(bd: &[i64], n_numeric: usize) -> Result<(usize, usize, usize, bool), ErrorInfo> {
    let (n_lhs_b, n_col, n_rhs) = match bd.len() {
        1 => (1, bd[0] as usize, 1),
        2 => {
            if n_numeric > 1 && bd[0] as usize == n_numeric {
                (bd[0] as usize, bd[1] as usize, 1)
            } else {
                (1, bd[0] as usize, bd[1] as usize)
            }
        }
        3 => (bd[0] as usize, bd[1] as usize, bd[2] as usize),
        _ => return Err(ErrorInfo::invalid("b must be 1D, 2D, or 3D")),
    };
    let broadcast_numeric = n_numeric == 1;
    let broadcast_b = n_lhs_b == 1;
    let n_lhs = if !broadcast_numeric && !broadcast_b {
        if n_numeric != n_lhs_b {
            return Err(ErrorInfo::invalid("numeric and b batch size mismatch"));
        }
        n_numeric
    } else if !broadcast_numeric {
        n_numeric
    } else if !broadcast_b {
        n_lhs_b
    } else {
        1
    };
    Ok((n_lhs, n_col, n_rhs, broadcast_b))
}

fn numeric_solve<T: Scalar>(
    sym: &Buf<u64>,
    numeric: &Buf<u64>,
    b: &Buf<T>,
    x: &mut BufMut<T>,
    transpose: bool,
) -> Result<(), ErrorInfo> {
    let (n_lhs, n_col, n_rhs, broadcast_b) = numeric_dims(b.dims(), numeric.len())?;
    let mut b_full = vec![T::zero(); n_lhs * n_col * n_rhs];
    for m in 0..n_lhs {
        let mb = if broadcast_b { 0 } else { m };
        for n in 0..n_col {
            for p in 0..n_rhs {
                b_full[m * n_col * n_rhs + n * n_rhs + p] = b[mb * n_col * n_rhs + n * n_rhs + p];
            }
        }
    }
    let out = engine::solve_with_numeric_raw(
        scalar_u64(sym)?,
        numeric,
        &b_full,
        n_lhs,
        n_col,
        n_rhs,
        transpose,
    )?;
    let n = x.len().min(out.len());
    x.as_mut_slice()[..n].copy_from_slice(&out[..n]);
    Ok(())
}

#[xla_handler(scalars(f64 => "solve_with_numeric_f64", C64 => "solve_with_numeric_c128"))]
fn solve_with_numeric<T: Scalar>(
    sym: Buf<u64>,
    numeric: Buf<u64>,
    b: Buf<T>,
    mut x: BufMut<T>,
) -> Result<(), ErrorInfo> {
    numeric_solve(&sym, &numeric, &b, &mut x, false)
}

#[xla_handler(scalars(f64 => "tsolve_with_numeric_f64", C64 => "tsolve_with_numeric_c128"))]
fn tsolve_with_numeric<T: Scalar>(
    sym: Buf<u64>,
    numeric: Buf<u64>,
    b: Buf<T>,
    mut x: BufMut<T>,
) -> Result<(), ErrorInfo> {
    numeric_solve(&sym, &numeric, &b, &mut x, true)
}

#[allow(clippy::too_many_arguments)]
#[xla_handler(scalars(f64 => "refactor_and_solve_f64", C64 => "refactor_and_solve_c128"))]
fn refactor_and_solve<T: Scalar>(
    ai: Buf<i32>,
    aj: Buf<i32>,
    ax: Buf<T>,
    b: Buf<T>,
    sym: Buf<u64>,
    numeric: Buf<u64>,
    mut x: BufMut<T>,
    mut out_numeric: BufMut<u64>,
) -> Result<(), ErrorInfo> {
    let (n_lhs, n_col, n_rhs) = dims3(b.dims())?;
    let handles = engine::refactor_batch_raw(&ai, &aj, &ax, n_lhs, scalar_u64(&sym)?, &numeric)?;
    let out = engine::solve_with_numeric_raw(
        scalar_u64(&sym)?,
        &handles,
        &b,
        n_lhs,
        n_col,
        n_rhs,
        false,
    )?;
    write(&mut x, &out)?;
    write(&mut out_numeric, &handles)
}

#[xla_handler(scalars(f64 => "dot_f64", C64 => "dot_c128"))]
fn dot<T: Scalar>(
    ai: Buf<i32>,
    aj: Buf<i32>,
    ax: Buf<T>,
    operand: Buf<T>,
    mut b: BufMut<T>,
) -> Result<(), ErrorInfo> {
    let (n_lhs, n_col, n_rhs) = dims3(operand.dims())?;
    let out = engine::dot_raw(&ai, &aj, &ax, &operand, n_lhs, n_col, n_rhs)?;
    write(&mut b, &out)
}

#[xla_handler(export = "free_symbolic")]
fn free_symbolic_h(symbolic: Buf<u64>, mut status: BufMut<i32>) -> Result<(), ErrorInfo> {
    let mut s = 0;
    for &addr in symbolic.iter() {
        s |= engine::free_symbolic_raw(addr);
    }
    status[0] = s;
    Ok(())
}

#[xla_handler(export = "free_numeric")]
fn free_numeric_h(numeric: Buf<u64>, mut status: BufMut<i32>) -> Result<(), ErrorInfo> {
    status[0] = engine::free_numeric_raw(&numeric);
    Ok(())
}
